#!/usr/bin env bash
#install Nginx server and configure it to listen on port 80

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

service nginx start
