#!/usr/bin/env bash
# install nginx on a server and configure it

apt-get update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

new_string="server_name _;\n\trewrite ^redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

service nginx restart
