#!/usr/bin env bash
#configure Nginx

sudo apt-get update
sudo apt-get -y install nginx

sudo chown -R "$USER":"$USER" /var/www

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html


sudo sed -i "48i\\\tif (\$request_filename ~ redirect_me){\n\t\t\
rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}" /etc/nginx/sites-available/default


string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
