#!/usr/bin/env bash
#Script that starts nginx as nginx user
pkill -9 apache
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
